#!/bin/bash

getUser() {
    user="$(whoami | tr '[:upper:]' '[:lower:]')"
}

getHostname() {
    hostname="$(hostname | tr '[:upper:]' '[:lower:]')"
}

getUptime() {
    uptime="$(uptime -p | sed 's/up //' | tr '[:upper:]' '[:lower:]')"
}

getOS() {
    os="$(lsb_release -ds | tr '[:upper:]' '[:lower:]')"
}

getCPU() {
    cpu="$(grep -i -m 1 'model name' /proc/cpuinfo | cut -f3- -d' ' | tr '[:upper:]' '[:lower:]')"
}

getRAM() {
    ram_use=$(free -m)
    IFS=$'\n' read -rd '' -a ram_use_arr <<< "$ram_use"
    ram_use="${ram_use_arr[1]}"
    ram_use=$(echo "$ram_use" | tr -s " ")
    IFS=' ' read -ra ram_use_arr <<< "$ram_use"
    total_ram="${ram_use_arr[1]}"
    ram_use="${ram_use_arr[2]}"
    ram_percnt="$((100*ram_use/total_ram))"
    ram="${ram_use}mb / ${total_ram}mb ${ram_percnt}%"
}

getPackages() {
    packages="$(dpkg --list | wc -l)"
}

getShell() {
    shell="$(basename $SHELL | tr '[:upper:]' '[:lower:]')"
}

getUser
getHostname
getUptime

getOS
getCPU
getRAM

getPackages
getShell

fetch() {
    echo -e "\n     ~ moonfetch\n"
    echo -e "\t    _.._       user\t  ::  \t$user@$hostname"
    echo -e "\t .' .-'\`       os\t  ::  \t$os"
    echo -e "\t/  /           uptime\t  ::  \t$uptime"
    echo -e "\t|  |           cpu\t  ::  \t$cpu"
    echo -e "\t\\  '.___.;     ram\t  ::  \t$ram"
    echo -e "\t '._  _.'      pkgs\t  ::  \t$packages"
    echo -e "\t    \`\`         shell\t  ::  \t$shell"
}

fetch
