#!/bin/bash

getUser() {
    user="$(whoami | tr '[:upper:]' '[:lower:]')"
}

getHostname() {
    hostname="$(hostname | tr '[:upper:]' '[:lower:]')"
}

getUptime() {
    uptime="$(uptime -p | sed 's/up //' | tr '[:upper:]' '[:lower:]')"
}

getOS() {
    os="$(lsb_release -ds | tr '[:upper:]' '[:lower:]')"
}

getCPU() {
    cpu="$(grep -i -m 1 'model name' /proc/cpuinfo | cut -f3- -d' ' | tr '[:upper:]' '[:lower:]')"
}

getRAM() {
    ram_avail="$(grep -i MemAvailable /proc/meminfo | awk '{print $2}')"
    ram_total="$(grep -i MemTotal /proc/meminfo | awk '{print $2}')"
    ram_used=$((ram_total - ram_avail))
    ((ram_used /= 1024))
    ((ram_avail /= 1024))
    ((ram_total /= 1024))
    ram_percnt=$((100*ram_used/ram_total))
    ram="$ram_used"
    ram+="mb / $ram_total"
    ram+="mb $ram_percnt%"
}

getPackages() {
    packages="$(dpkg --list | wc -l)"
}

getShell() {
    shell="$(basename $SHELL | tr '[:upper:]' '[:lower:]')"
}

getUser
getHostname
getUptime

getOS
getCPU
getRAM

getPackages
getShell

fetch() {
    echo -e "\n     ~ moonfetch\n"
    echo -e "\t    _.._       user\t  ::  \t$user@$hostname"
    echo -e "\t .' .-'\`       os\t  ::  \t$os"
    echo -e "\t/  /           uptime\t  ::  \t$uptime"
    echo -e "\t|  |           cpu\t  ::  \t$cpu"
    echo -e "\t\\  '.___.;     ram\t  ::  \t$ram"
    echo -e "\t '._  _.'      pkgs\t  ::  \t$packages"
    echo -e "\t    \`\`         shell\t  ::  \t$shell"
}

fetch
